### ISSUE TITLE
Scrape Intervall

### ISSUE THREAD

**Issue by linokaiserWGC** [anas-aso/ssllabs_exporter#39]
How often does the exporter scrape a target? 

Is there a way to influence/change the scrape intervall? 

Thanks

**Comment by anas-aso** [comment]
@linokaiserWGC that's something you configure yourself as show in [this example](https://github.com/anas-aso/ssllabs_exporter/blob/21ca8c1545b015d6437aa05a3701224f4559104d/examples/prometheus/static_targets.yaml#L3). 
The exporter doesn't scrape targets on its own. You have to request it (via a Prometheus scrape job) to scrape them.
Just make sure the scrape interval is high enough since SSLLabs assesments take a couple of minutes to finish.

**Comment by linokaiserWGC** [comment]
Ah so it really depends on the scrape intervall defined for the job in prometheus. Thats a cool functionality. Thanks for the quick answer. You can close the issue.
